// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMPdTH615Wr_1Y_f41VCfYxd798Ygfzk0',
    appId: '1:782348514985:web:32ea44406e043a851f9bb8',
    messagingSenderId: '782348514985',
    projectId: 'first-project-f1c0b',
    authDomain: 'first-project-f1c0b.firebaseapp.com',
    databaseURL: 'https://first-project-f1c0b-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-f1c0b.appspot.com',
    measurementId: 'G-QWDGM2C7M8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOx2iVPjI5Qh2hKqOEZnvuxkH4FIPePQM',
    appId: '1:782348514985:android:2575b6a2bdc34f9a1f9bb8',
    messagingSenderId: '782348514985',
    projectId: 'first-project-f1c0b',
    databaseURL: 'https://first-project-f1c0b-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-f1c0b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZaP_Reae__KvhRezbGvP9z7zX-IBoKFU',
    appId: '1:782348514985:ios:e3ae0d30b16c2fb71f9bb8',
    messagingSenderId: '782348514985',
    projectId: 'first-project-f1c0b',
    databaseURL: 'https://first-project-f1c0b-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-f1c0b.appspot.com',
    iosBundleId: 'com.example.cat3',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZaP_Reae__KvhRezbGvP9z7zX-IBoKFU',
    appId: '1:782348514985:ios:e3ae0d30b16c2fb71f9bb8',
    messagingSenderId: '782348514985',
    projectId: 'first-project-f1c0b',
    databaseURL: 'https://first-project-f1c0b-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-f1c0b.appspot.com',
    iosBundleId: 'com.example.cat3',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBMPdTH615Wr_1Y_f41VCfYxd798Ygfzk0',
    appId: '1:782348514985:web:dd78be0b2a1a73ad1f9bb8',
    messagingSenderId: '782348514985',
    projectId: 'first-project-f1c0b',
    authDomain: 'first-project-f1c0b.firebaseapp.com',
    databaseURL: 'https://first-project-f1c0b-default-rtdb.firebaseio.com',
    storageBucket: 'first-project-f1c0b.appspot.com',
    measurementId: 'G-TQ48RC0FEY',
  );
}
